title: Luca Mondada
author: Luca Mondada
tagline: Quantum Machine Learning PhD

email: luca.mondada@cs.ox.ac.uk
placeholder_email: first name at last name dot net
encoded_email: "&#107;&#117;&#046;&#099;&#097;&#046;&#120;&#111;&#046;&#115;&#099;&#064;&#097;&#100;&#097;&#100;&#110;&#111;&#109;&#046;&#097;&#099;&#117;&#108;"

description: >- # this means to ignore newlines until "baseurl:"
  "Close-to-done" PhD student at the University of Oxford and Software Engineer at
  Quantinuum.
  My research interests lie mainly in the intersection of quantum compilation,
  graph transformation systems and high-performance computing for Quantum.
  I previously obtained a MSc in Mathematics and Foundation of Computer Science
  (with Distinction) at the University of Oxford
  and two BSc degrees in Physics and Computer Science at ETH Zürich.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://luca.mondada.net" # the base hostname & protocol for your site, e.g. http://example.com

# twitter_username: jekyllrb
twitter:
  username: lmondada
  card: summary_large_image

social:
  name: Luca Mondada
  links:
    - https://github.com/lmondada
    - https://twitter.com/lmondada
    - https://www.linkedin.com/in/lmondada

github_username:  lmondada

theme: moonwalk
theme_config:
  appearance: "auto"
kramdown:
  entity_output: :as_input

plugins:
  - jekyll-feed
  - jekyll-seo-tag


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
